// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RestaurantPaymentSystem.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20220223194813_SeedDishes")]
    partial class SeedDishes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DishModelTableModel", b =>
                {
                    b.Property<int>("DishModelsDishId")
                        .HasColumnType("int");

                    b.Property<int>("TableModelsTableId")
                        .HasColumnType("int");

                    b.HasKey("DishModelsDishId", "TableModelsTableId");

                    b.HasIndex("TableModelsTableId");

                    b.ToTable("DishModelTableModel");
                });

            modelBuilder.Entity("RestaurantPaymentSystem.Data.Models.DishModel", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"), 1L, 1);

                    b.Property<string>("DishName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DishPrice")
                        .HasColumnType("float");

                    b.HasKey("DishId");

                    b.ToTable("DishModels");
                });

            modelBuilder.Entity("RestaurantPaymentSystem.Data.Models.TableModel", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"), 1L, 1);

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.ToTable("TableModels");
                });

            modelBuilder.Entity("DishModelTableModel", b =>
                {
                    b.HasOne("RestaurantPaymentSystem.Data.Models.DishModel", null)
                        .WithMany()
                        .HasForeignKey("DishModelsDishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantPaymentSystem.Data.Models.TableModel", null)
                        .WithMany()
                        .HasForeignKey("TableModelsTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
